export const DATA_STATE_NOT_REQUESTED = "DATA_NOT_REQUESTED";
export const DATA_STATE_REQUESTING = "REQUESTING_DATA";
export const DATA_STATE_RECEIVED = "DATA_RECEIVED";
export const DATA_STATE_ERROR = "ERROR";


