export const GET_CHARACTERS = "GET_CHARACTERS";
export const GET_CHARACTER = "GET_CHARACTER";

export const REQUEST_GET_CHARACTERS = `REQUEST_${GET_CHARACTERS}`;
export const RESPONSE_GET_CHARACTERS = `RESPONSE_${GET_CHARACTERS}`;
export const RESPONSE_GET_CHARACTERS_ERROR = `RESPONSE_ERROR_${GET_CHARACTERS}`;

export const REQUEST_GET_CHARACTER = `REQUEST_${GET_CHARACTER}`;
export const RESPONSE_GET_CHARACTER = `RESPONSE_${GET_CHARACTER}`;
export const RESPONSE_GET_CHARACTER_ERROR = `RESPONSE_ERROR_${GET_CHARACTER}`;

